{
  "contest": 271,
  "handle": "seerether",
  "risk": "3",
  "title": "rngComplete() function is vulnerable to an array out of bounds error",
  "issueId": 136,
  "issueUrl": "https://github.com/code-423n4/2023-08-pooltogether-findings/issues/136"
}